---
wandb_target_run: model_inversion_targets_celeba/xxxxxxx
wandb_evaluation_run: model_inversion_evaluation/xxxxxxx
stylegan_model: stylegan2-ada-pytorch/metfaces.pkl
seed: 42
dataset: celeba_identities

candidates:
  num_candidates: 400
  candidate_search:
    search_space_size: 5000
    center_crop: 800
    resize: 224
    horizontal_flip: true
    batch_size: 20
    truncation_psi: 0.5
    truncation_cutoff: 8

attack:
  batch_size: 20
  num_epochs: 70
  targets: [30,8,32,33,0,38]
  discriminator_loss_weight: 0.0
  single_w: true
  clip: false
  transformations:
    CenterCrop:
      size: 800
    Resize:
      size: 224
    RandomResizedCrop:
      size: [224, 224]
      scale: [0.9, 1.0]
      ratio: [1.0, 1.0]

  optimizer:
    Adam:
      lr: 0.005
      weight_decay: 0
      betas: [0.1, 0.1]

final_selection:
  samples_per_target: 50
  approach: transforms 
  iterations: 100


wandb:
  enable_logging: true
  wandb_init_args:
    project: model_inversion_attacks
    save_code: true
    name: Attack_CelebA_MetFaces